name: Build and Push sqlapi

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SQLAPI: techciceksepeti/sqlapi
      TAG_SQLAPI: latest

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          echo "$SECRETS_CONTEXT" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER  }}
          password: ${{ secrets.DOCKER_PASS  }}

      - name: Build and Push sqlapi Docker Image
        run: |
          bash ./build-image-multi-platform.sh $SQLAPI Dockerfile $TAG_SQLAPI
